export const classItem = {
  canyin: "餐饮",
  jiaotong: "交通",
  gouwu: "购物",
  shuiguo: "水果",
  shuma: "数码",
  yanjiu: "烟酒",
  riyong: "生活日用",
  yiliao: "医疗",
  tongxun: "通讯",
  yundong: "运动",
  yifu: "服饰",
  shejiao: "社交",
  yule: "娱乐",
  huazhuangpin: "化妆品",
  lvxing: "旅行",
  chongwu: "宠物",
  haizi: "孩子",
  qiche: "汽车",
  qita: "其他",
  shezhi: "自定义",
}